# Generated by Django 4.1 on 2022-08-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_avion', models.CharField(max_length=20)),
                ('codigo_avion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_base', models.CharField(max_length=20)),
                ('ciudad_base', models.CharField(max_length=20)),
                ('latitud_base', models.FloatField()),
                ('longitud_base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_miembro', models.CharField(max_length=20)),
                ('nombre_miembro', models.CharField(max_length=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aeropuerto_app.base')),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_piloto', models.CharField(max_length=20, unique=True)),
                ('nombre_piloto', models.CharField(max_length=20)),
                ('horas_vuelo_piloto', models.IntegerField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aeropuerto_app.base')),
            ],
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tripulacion', models.CharField(max_length=20)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aeropuerto_app.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(max_length=10)),
                ('origen', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=20)),
                ('hora_vuelo', models.DateTimeField()),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aeropuerto_app.avion')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aeropuerto_app.piloto')),
                ('tripulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aeropuerto_app.tripulacion')),
            ],
        ),
        migrations.AddField(
            model_name='avion',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aeropuerto_app.base'),
        ),
    ]
