# Generated by Django 4.1 on 2022-08-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeropuerto_app', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
