# Generated by Django 4.1 on 2022-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeropuerto_app', '0003_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
